sudo: 'required'
language: go
go:
  - 1.11.5

services:
  - 'docker'
env:
  - GO111MODULE=on
jobs:
  include:
    - stage: build
      script:
        - go install -v ./...
        - CGO_ENABLED=0 go build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t plumealerts/streamannotations-backend:0.0.$TRAVIS_BUILD_NUMBER .
        - docker push plumealerts/streamannotations-backend:0.0.$TRAVIS_BUILD_NUMBER